# Generated by Django 5.1.15 on 2026-08-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_per_user_email_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('task_assigned', 'Task assigned'), ('due_soon', 'Due date approaching'), ('overdue', 'Task overdue'), ('overdue_ack', 'Overdue — acknowledgement required'), ('dependency_done', 'Dependency completed'), ('review_requested', 'Review requested'), ('review_decision', 'Review decision'), ('mention', 'Mention'), ('comment', 'Comment'), ('direct_message', 'Direct message'), ('blocker_raised', 'Blocker raised'), ('decision_requested', 'Decision requested'), ('project_at_risk', 'Project at risk'), ('sprint_event', 'Sprint event'), ('approval_granted', 'Approval granted'), ('deadline_change', 'Deadline change requested'), ('doc_expiring', 'Document expiring'), ('sop_review_due', 'SOP review due'), ('registration_due', 'Registration renewal due'), ('duration_complete', 'Workspace project duration complete'), ('ack_received', 'Acknowledgement received'), ('automation', 'Automation'), ('digest', 'Daily digest')], max_length=30),
        ),
    ]
