# Generated by Django 5.1.4 on 2026-08-17 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_messageattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direct_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.directmessage')),
                ('group_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.groupmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('direct_message__isnull', False), ('group_message__isnull', True)), models.Q(('direct_message__isnull', True), ('group_message__isnull', False)), _connector='OR'), name='reaction_exactly_one_parent'), models.UniqueConstraint(condition=models.Q(('direct_message__isnull', False)), fields=('direct_message', 'user'), name='uniq_dm_reaction_per_user'), models.UniqueConstraint(condition=models.Q(('group_message__isnull', False)), fields=('group_message', 'user'), name='uniq_group_reaction_per_user')],
            },
        ),
    ]
