# Generated by Django 5.1.4 on 2026-08-17 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_messagereaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typing_states', to='messaging.conversation')),
                ('group_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typing_states', to='messaging.groupthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('conversation__isnull', False), ('group_thread__isnull', True)), models.Q(('conversation__isnull', True), ('group_thread__isnull', False)), _connector='OR'), name='typing_exactly_one_parent'), models.UniqueConstraint(condition=models.Q(('conversation__isnull', False)), fields=('conversation', 'user'), name='uniq_dm_typing'), models.UniqueConstraint(condition=models.Q(('group_thread__isnull', False)), fields=('group_thread', 'user'), name='uniq_group_typing')],
            },
        ),
    ]
