# Generated by Django 5.1.15 on 2026-07-29 08:00

import apps.ai.providers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('page_path', models.CharField(blank=True, max_length=300)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aiconversation')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('chat', 'Chat'), ('summarize', 'Summarize'), ('rewrite', 'Rewrite'), ('translate', 'Translate'), ('generate_email', 'Generate email'), ('analyse_tasks', 'Analyse tasks'), ('analyse_project', 'Analyse project'), ('generate_notifications', 'Generate notifications'), ('create_tasks_from_notes', 'Create tasks from notes'), ('project_summary', 'Project summary'), ('risk_analysis', 'Risk analysis'), ('delay_prediction', 'Delay prediction'), ('health_score', 'Health score'), ('subtasks', 'Generate subtasks'), ('estimate', 'Estimate effort'), ('prioritize', 'Prioritise'), ('meeting_summary', 'Meeting summary'), ('customer_summary', 'Customer summary'), ('draft_reply', 'Draft customer reply'), ('proposal', 'Generate proposal'), ('job_description', 'Job description'), ('performance_summary', 'Performance summary'), ('insights', 'Dashboard insights'), ('explain_stats', 'Explain statistics'), ('report', 'Generate report'), ('duplicate_detection', 'Duplicate detection'), ('workload', 'Workload balancing')], db_index=True, max_length=40)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('subject_type', models.CharField(blank=True, max_length=60)),
                ('subject_id', models.CharField(blank=True, max_length=40)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, max_length=400)),
                ('structured', models.BooleanField(default=False, help_text='Response parsed as valid JSON.')),
                ('prompt_chars', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('response_preview', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIAutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('overdue_reminder', 'Overdue reminder'), ('overdue_repeat', 'Repeat reminder'), ('manager_notified', 'Manager notified'), ('escalated', 'Escalated'), ('blocked_task', 'Blocked task'), ('high_priority', 'High-priority task attention'), ('sla_violation', 'SLA violation'), ('project_health', 'Project health analysis'), ('critical_status', 'Critical status'), ('daily_summary', 'Daily summary'), ('weekly_report', 'Weekly report'), ('monthly_report', 'Monthly report'), ('milestone_missed', 'Milestone missed')], db_index=True, max_length=30)),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('executed_actions', models.JSONField(blank=True, default=list, help_text='e.g. ["notified:3", "email:2", "priority:high"]')),
                ('ok', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_automation_logs', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_automation_logs', to='tasks.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_automation_logs', to=settings.AUTH_USER_MODEL)),
                ('request_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_logs', to='ai.airequestlog')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=apps.ai.providers.provider_choices, default='grok', max_length=20)),
                ('model', models.CharField(blank=True, help_text="Blank uses the provider's default model.", max_length=80)),
                ('base_url', models.CharField(blank=True, help_text='Override the provider endpoint (self-hosted / proxy).', max_length=200)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.PositiveIntegerField(default=1200)),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('is_enabled', models.BooleanField(default=True, help_text='Turn every AI feature off at once.')),
                ('automation_enabled', models.BooleanField(default=True, help_text='Run the scheduled AI scans.')),
                ('email_enabled', models.BooleanField(default=True, help_text='Let automations send email.')),
                ('overdue_scan_enabled', models.BooleanField(default=True)),
                ('blocked_scan_enabled', models.BooleanField(default=True)),
                ('health_scan_enabled', models.BooleanField(default=True)),
                ('daily_summary_enabled', models.BooleanField(default=True)),
                ('weekly_report_enabled', models.BooleanField(default=True)),
                ('monthly_report_enabled', models.BooleanField(default=True)),
                ('reminder_repeat_minutes', models.PositiveIntegerField(default=30, help_text='Repeat the reminder this many minutes after the first.')),
                ('manager_notify_hours', models.PositiveIntegerField(default=2, help_text='Notify the project manager after this many hours overdue.')),
                ('escalate_hours', models.PositiveIntegerField(default=24, help_text='Escalate to project owner / management after this many hours.')),
                ('max_calls_per_hour', models.PositiveIntegerField(default=500, help_text='Safety cap on provider calls per hour across the whole system. 0 = unlimited.')),
                ('max_items_per_scan', models.PositiveIntegerField(default=50, help_text='Most records one scheduled scan will process in a single run.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI settings',
                'verbose_name_plural': 'AI settings',
            },
        ),
        migrations.CreateModel(
            name='TaskEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(choices=[(0, 'Not yet reminded'), (1, 'Owner reminded'), (2, 'Reminder repeated'), (3, 'Manager notified'), (4, 'Escalated to management')], default=0)),
                ('first_detected_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('manager_notified_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_escalation', to='tasks.task')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=240)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('content', models.JSONField(blank=True, default=dict, help_text='Structured report body from the AI.')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='The figures the report was built from.')),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-period_end', '-created_at'),
                'indexes': [models.Index(fields=['period', 'period_end'], name='ai_aireport_period_bc4b53_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['action', 'created_at'], name='ai_aireques_action_e853fb_idx'),
        ),
        migrations.AddIndex(
            model_name='aiautomationlog',
            index=models.Index(fields=['event', 'created_at'], name='ai_aiautoma_event_0d0dc7_idx'),
        ),
    ]
