# Generated by Django 5.1.15 on 2026-07-30 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='executive_daily_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='executive_email_enabled',
            field=models.BooleanField(default=True, help_text='Email each generated executive summary to leadership.'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='executive_monthly_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='executive_summary_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for the AI executive summary.'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='executive_weekly_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='standup_email_enabled',
            field=models.BooleanField(default=True, help_text="Email the stand-up (still honours each user's own preferences)."),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='standup_enabled',
            field=models.BooleanField(default=True, help_text='Generate the AI daily stand-up.'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='standup_hour',
            field=models.PositiveSmallIntegerField(default=9, help_text='Local hour the stand-up is generated at (0-23).'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='standup_minute',
            field=models.PositiveSmallIntegerField(default=0, help_text='Local minute the stand-up is generated at (0-59).'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='standup_notify_enabled',
            field=models.BooleanField(default=True, help_text='Raise an in-app notification when a stand-up is ready.'),
        ),
        migrations.AlterField(
            model_name='aiautomationlog',
            name='event',
            field=models.CharField(choices=[('overdue_reminder', 'Overdue reminder'), ('overdue_repeat', 'Repeat reminder'), ('manager_notified', 'Manager notified'), ('escalated', 'Escalated'), ('blocked_task', 'Blocked task'), ('high_priority', 'High-priority task attention'), ('sla_violation', 'SLA violation'), ('project_health', 'Project health analysis'), ('critical_status', 'Critical status'), ('daily_summary', 'Daily summary'), ('weekly_report', 'Weekly report'), ('monthly_report', 'Monthly report'), ('milestone_missed', 'Milestone missed'), ('daily_standup', 'Daily stand-up'), ('executive_summary', 'Executive summary')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='action',
            field=models.CharField(choices=[('chat', 'Chat'), ('summarize', 'Summarize'), ('rewrite', 'Rewrite'), ('translate', 'Translate'), ('generate_email', 'Generate email'), ('analyse_tasks', 'Analyse tasks'), ('analyse_project', 'Analyse project'), ('generate_notifications', 'Generate notifications'), ('create_tasks_from_notes', 'Create tasks from notes'), ('project_summary', 'Project summary'), ('risk_analysis', 'Risk analysis'), ('delay_prediction', 'Delay prediction'), ('health_score', 'Health score'), ('subtasks', 'Generate subtasks'), ('estimate', 'Estimate effort'), ('prioritize', 'Prioritise'), ('meeting_summary', 'Meeting summary'), ('customer_summary', 'Customer summary'), ('draft_reply', 'Draft customer reply'), ('proposal', 'Generate proposal'), ('job_description', 'Job description'), ('performance_summary', 'Performance summary'), ('insights', 'Dashboard insights'), ('explain_stats', 'Explain statistics'), ('report', 'Generate report'), ('duplicate_detection', 'Duplicate detection'), ('workload', 'Workload balancing'), ('daily_standup', 'Daily stand-up'), ('executive_summary', 'Executive summary')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='DailyStandup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Structured body from the AI.')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='The figures it was built from.')),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=10)),
                ('ai_ok', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, max_length=400)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('standup_date', models.DateField(db_index=True)),
                ('generation_count', models.PositiveIntegerField(default=1)),
                ('generated_by', models.ForeignKey(blank=True, help_text='Who pressed the button. Null for scheduled runs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.airequestlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_standups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-standup_date', '-created_at'),
                'indexes': [models.Index(fields=['user', 'standup_date'], name='ai_dailysta_user_id_b83862_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'standup_date'), name='unique_standup_per_user_per_day')],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Structured body from the AI.')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='The figures it was built from.')),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=10)),
                ('ai_ok', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, max_length=400)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('title', models.CharField(blank=True, max_length=240)),
                ('health_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_count', models.PositiveSmallIntegerField(default=0)),
                ('generation_count', models.PositiveIntegerField(default=1)),
                ('generated_by', models.ForeignKey(blank=True, help_text='Who pressed the button. Null for scheduled runs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.airequestlog')),
            ],
            options={
                'ordering': ('-period_end', '-created_at'),
                'indexes': [models.Index(fields=['period', 'period_end'], name='ai_executiv_period_e2395c_idx')],
                'constraints': [models.UniqueConstraint(fields=('period', 'period_end'), name='unique_executive_summary_per_period')],
            },
        ),
    ]
