# Generated by Django 5.1.15 on 2026-07-30 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aisettings_executive_daily_enabled_and_more'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='critical_alert_bcc',
            field=models.TextField(blank=True, help_text='Comma or newline separated addresses blind-copied on every critical alert.'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='critical_alert_cooldown_hours',
            field=models.PositiveIntegerField(default=12, help_text='Do not re-alert on the same task within this many hours.'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='critical_alert_enabled',
            field=models.BooleanField(default=True, help_text='Email immediately when a task reaches a critical stage.'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='critical_alert_include_managers',
            field=models.BooleanField(default=True, help_text='Copy the project manager and owner on critical alerts.'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='outbound_email_enabled',
            field=models.BooleanField(default=True, help_text='Let users send email to external addresses from KOS.'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='outbound_hourly_limit_per_user',
            field=models.PositiveIntegerField(default=30, help_text='Messages one user may send per hour. 0 = unlimited.'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='outbound_max_recipients',
            field=models.PositiveSmallIntegerField(default=25, help_text='Most addresses one message may reach across To, Cc and Bcc combined.'),
        ),
        migrations.AlterField(
            model_name='aiautomationlog',
            name='event',
            field=models.CharField(choices=[('overdue_reminder', 'Overdue reminder'), ('overdue_repeat', 'Repeat reminder'), ('manager_notified', 'Manager notified'), ('escalated', 'Escalated'), ('blocked_task', 'Blocked task'), ('high_priority', 'High-priority task attention'), ('sla_violation', 'SLA violation'), ('project_health', 'Project health analysis'), ('critical_status', 'Critical status'), ('critical_task', 'Task reached a critical stage'), ('daily_summary', 'Daily summary'), ('weekly_report', 'Weekly report'), ('monthly_report', 'Monthly report'), ('milestone_missed', 'Milestone missed'), ('daily_standup', 'Daily stand-up'), ('executive_summary', 'Executive summary')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='OutboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to', models.JSONField(default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('reply_to', models.CharField(blank=True, max_length=320)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('source', models.CharField(choices=[('manual', 'Sent by a user'), ('critical_alert', 'Critical task alert')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=10)),
                ('error', models.CharField(blank=True, max_length=400)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('draft_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='ai.airequestlog')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_emails', to='projects.project')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_emails', to='tasks.task')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='ai_outbound_status_4ab1b1_idx'), models.Index(fields=['sender', 'created_at'], name='ai_outbound_sender__9041e7_idx')],
            },
        ),
    ]
