# Generated by Django 5.1.15 on 2026-08-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aisettings_critical_alert_bcc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequestlog',
            name='action',
            field=models.CharField(choices=[('chat', 'Chat'), ('transcribe', 'Transcribe speech'), ('summarize', 'Summarize'), ('rewrite', 'Rewrite'), ('translate', 'Translate'), ('generate_email', 'Generate email'), ('analyse_tasks', 'Analyse tasks'), ('analyse_project', 'Analyse project'), ('generate_notifications', 'Generate notifications'), ('create_tasks_from_notes', 'Create tasks from notes'), ('project_summary', 'Project summary'), ('risk_analysis', 'Risk analysis'), ('delay_prediction', 'Delay prediction'), ('health_score', 'Health score'), ('subtasks', 'Generate subtasks'), ('estimate', 'Estimate effort'), ('prioritize', 'Prioritise'), ('meeting_summary', 'Meeting summary'), ('customer_summary', 'Customer summary'), ('draft_reply', 'Draft customer reply'), ('proposal', 'Generate proposal'), ('job_description', 'Job description'), ('performance_summary', 'Performance summary'), ('insights', 'Dashboard insights'), ('explain_stats', 'Explain statistics'), ('report', 'Generate report'), ('duplicate_detection', 'Duplicate detection'), ('workload', 'Workload balancing'), ('daily_standup', 'Daily stand-up'), ('executive_summary', 'Executive summary'), ('workspace_scaffold', 'Build workspace project from a prompt')], db_index=True, max_length=40),
        ),
    ]
