# Generated by Django 5.1.4 on 2026-07-28 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(help_text="Stable key, e.g. 'notification'.", max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('retention_days', models.PositiveIntegerField(blank=True, help_text='Delete records older than this. Null = keep indefinitely.', null=True)),
                ('is_exempt', models.BooleanField(default=False, help_text='Never purged — audit trail & regulatory records (§26.4).')),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'retention policies',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('ownership_change', 'Ownership Change'), ('deadline_change', 'Deadline Change'), ('workflow_change', 'Workflow Change'), ('approve', 'Approve'), ('reject', 'Reject'), ('request_changes', 'Request Changes'), ('notification_ack', 'Notification Acknowledgement'), ('export', 'Export Data'), ('role_change', 'Role Change'), ('permission_change', 'Permission Change'), ('membership_change', 'Membership Change'), ('mfa_change', 'MFA Change')], max_length=40)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null when the action was performed by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
