# Generated by Django 5.1.4 on 2026-07-28 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(blank=True, help_text='Assigned by the authority on approval.', max_length=120)),
                ('authority', models.CharField(choices=[('cibrc', 'CIBRC (Central Insecticides Board & Registration Committee)'), ('epa', 'US EPA'), ('state', 'State Agriculture Department'), ('other', 'Other')], default='cibrc', max_length=20)),
                ('category', models.CharField(blank=True, help_text='e.g. Insecticide, Fungicide, Herbicide.', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('query_raised', 'Query raised'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('renewal_due', 'Renewal due'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reminder_lead_days', models.PositiveIntegerField(default=60)),
                ('expiry_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='registrations', to='documents.document')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_registrations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='projects.project')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
