# Generated by Django 5.1.4 on 2026-08-06 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimate_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minutes', models.PositiveIntegerField()),
                ('spent_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-spent_on', '-created_at'),
                'indexes': [models.Index(fields=['user', 'spent_on'], name='tasks_timee_user_id_b0a9e3_idx'), models.Index(fields=['task'], name='tasks_timee_task_id_9e7736_idx')],
            },
        ),
    ]
