# Generated by Django 5.1.4 on 2026-08-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_estimate_minutes_timeentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='estimate_minutes',
        ),
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
