# Generated by Django 5.1.4 on 2026-07-28 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('trigger', models.CharField(choices=[('task_created', 'When a task is created'), ('task_status_changed', "When a task's status changes"), ('task_completed', 'When a task is completed'), ('task_overdue', 'When a task becomes overdue'), ('task_due_soon', 'When a task is due soon'), ('blocker_raised', 'When a blocker is raised'), ('approval_decided', 'When an approval is decided')], max_length=30)),
                ('conditions', models.JSONField(blank=True, default=list, help_text='[{"field","op","value"}] — all must hold.')),
                ('actions', models.JSONField(blank=True, default=list, help_text='[{"type", ...params}] — run in order.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='projects.project')),
            ],
            options={
                'ordering': ('project_id', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(blank=True, max_length=160)),
                ('trigger', models.CharField(choices=[('task_created', 'When a task is created'), ('task_status_changed', "When a task's status changes"), ('task_completed', 'When a task is completed'), ('task_overdue', 'When a task becomes overdue'), ('task_due_soon', 'When a task is due soon'), ('blocker_raised', 'When a blocker is raised'), ('approval_decided', 'When an approval is decided')], max_length=30)),
                ('actions_run', models.JSONField(blank=True, default=list)),
                ('ok', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_logs', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_logs', to='tasks.task')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.automationrule')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
