# Generated by Django 5.1.4 on 2026-07-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacerecord',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='workspace_records/'),
        ),
    ]
