# Generated by Django 5.1.4 on 2026-07-29 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspacesection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='workspacesection',
            name='uniq_workspace_section',
        ),
        migrations.RemoveIndex(
            model_name='workspacerecord',
            name='workspaces__workspa_4d8796_idx',
        ),
        migrations.AddField(
            model_name='workspaceproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacerecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='workspaces.workspaceproject'),
        ),
        migrations.AddField(
            model_name='workspacesection',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='workspaces.workspaceproject'),
        ),
        migrations.AddIndex(
            model_name='workspacerecord',
            index=models.Index(fields=['project', 'category'], name='workspaces__project_b2ec9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacesection',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_project_section'),
        ),
        migrations.AddConstraint(
            model_name='workspaceproject',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_workspace_project'),
        ),
    ]
