# Generated by Django 5.1.4 on 2026-07-29 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workspaces', '0004_workspaceproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspacePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(max_length=64)),
                ('access', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='view', max_length=8)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_permissions', to='accounts.role')),
            ],
            options={
                'ordering': ('workspace',),
                'constraints': [models.UniqueConstraint(fields=('role', 'workspace'), name='uniq_role_workspace_perm')],
            },
        ),
    ]
