# Generated by Django 5.1.4 on 2026-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_workspacepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceproject',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceproject',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceproject',
            name='duration_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceproject',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
