# Generated by Django 5.1.4 on 2026-07-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workspacerecord_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceproject',
            name='reminders_sent',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
