# Generated by Django 5.1.4 on 2026-07-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_workspaceproject_reminders_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceproject',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceproject',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacerecord',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacerecord',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
