# Generated by Django 5.1.4 on 2026-07-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_backfill_duration_datetimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesection',
            name='fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
