# Generated by Django 5.1.4 on 2026-07-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_workspacesection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesection',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
