# Generated by Django 5.1.4 on 2026-08-04 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0017_remove_workspaceproject_uniq_workspace_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.CharField(max_length=64)),
                ('access', models.CharField(choices=[('hidden', 'Hidden'), ('view', 'View'), ('edit', 'Edit')], max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user_id', 'workspace'),
                'constraints': [models.UniqueConstraint(fields=('user', 'workspace'), name='uniq_user_workspace_override')],
            },
        ),
    ]
