# Generated by Django 5.1.4 on 2026-08-07 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0018_workspaceuseraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceRecordAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='workspace_records/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workspaces.workspacerecord')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
