# Generated by Django 5.1.15 on 2026-08-07 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0019_workspacerecordattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspacesection',
            name='uniq_project_section_active',
        ),
        migrations.AddField(
            model_name='workspacerecord',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='workspaces.workspacesection'),
        ),
        migrations.AddField(
            model_name='workspacesection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workspaces.workspacesection'),
        ),
        migrations.AlterField(
            model_name='workspacerecord',
            name='category',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='workspacesection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', True)), fields=('project', 'name'), name='uniq_project_root_section_active'),
        ),
        migrations.AddConstraint(
            model_name='workspacesection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('parent__isnull', False)), fields=('project', 'parent', 'name'), name='uniq_project_child_section_active'),
        ),
    ]
