# Generated by Django 5.1.15 on 2026-08-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0021_link_records_to_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesection',
            name='builtin_key',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
