# Generated by Django 5.1.15 on 2026-08-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0022_workspacesection_builtin_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacesection',
            name='builtin_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
