# Generated by Django 5.1.15 on 2026-08-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0023_alter_workspacesection_builtin_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_builtin',
            field=models.BooleanField(default=False),
        ),
    ]
