# Generated by Django 5.1.4 on 2026-08-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0025_workspaceprojectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceproject',
            name='review_state',
            field=models.CharField(blank=True, choices=[('', 'None'), ('blocked', 'Blocked'), ('needs_decision', 'Needs decision')], default='', max_length=16),
        ),
    ]
