# Generated by Django 5.1.15 on 2026-08-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0027_workspaceproject_review_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceproject',
            name='next_occurrence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_occurrence', to='workspaces.workspaceproject'),
        ),
        migrations.AddField(
            model_name='workspaceproject',
            name='repeat_frequency',
            field=models.CharField(blank=True, choices=[('', 'Does not repeat'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='', max_length=12),
        ),
    ]
