# Generated by Django 5.1.4 on 2026-07-28 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.URLField(help_text='Endpoint that receives outbound events.')),
                ('secret', models.CharField(blank=True, help_text='Shared key for HMAC-SHA256 signing.', max_length=255)),
                ('auth_scheme', models.CharField(choices=[('none', 'None'), ('bearer', 'Bearer token'), ('header', 'Custom header')], default='none', max_length=10)),
                ('auth_token', models.CharField(blank=True, help_text='Bearer token or custom-header value.', max_length=255)),
                ('auth_header_name', models.CharField(blank=True, default='X-API-Key', max_length=80)),
                ('subscribed_events', models.JSONField(blank=True, default=list, help_text='EventType values this ERP wants.')),
                ('is_active', models.BooleanField(default=True)),
                ('inbound_enabled', models.BooleanField(default=False)),
                ('mock_mode', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=12)),
                ('result', models.CharField(blank=True, max_length=300)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_events', to='integrations.erpconnection')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('project.created', 'Project created'), ('project.updated', 'Project updated'), ('task.created', 'Task created'), ('task.status_changed', 'Task status changed'), ('task.completed', 'Task completed'), ('approval.decided', 'Approval decided'), ('ping', 'Test ping')], max_length=40)),
                ('object_type', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('mocked', 'Mocked (simulated)')], default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.erpconnection')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='integration_status_9e3d5d_idx')],
            },
        ),
    ]
